CREATE TABLE ROLES(
	ID VARCHAR(37) NOT NULL,
	NAME VARCHAR (100) NOT NULL,
	DESCRIPTION VARCHAR (250),
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID) 
);

CREATE TABLE GENDER(
	ID VARCHAR(37) NOT NULL,
	CODE VARCHAR(3) NOT NULL,
	NAME VARCHAR (100) NOT NULL,
	DESCRIPTION VARCHAR (250),
	CREATED_SID   VARCHAR(37) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_SID   VARCHAR(37),
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID)
);
REATE TABLE COUNTRY(
	ID VARCHAR(37) NOT NULL,
	CODE VARCHAR(9) NOT NULL,
	NAME VARCHAR(200) NOT NULL,
	ORDER_NUM INT,
	CREATED_SID   VARCHAR(37) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_SID   VARCHAR(37),
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID)
);



CREATE TABLE CURRENCY( 
	ID VARCHAR(37) NOT NULL,
	CODE VARCHAR (10) NOT NULL,
	NAME VARCHAR (100) NOT NULL,
	SYMBOL  VARCHAR(30),
    CREATED_SID   VARCHAR(37) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_SID   VARCHAR(37),
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE STATUS (
	ID VARCHAR(37) NOT NULL,	
	CODE VARCHAR (50) NOT NULL,	
	NAME VARCHAR (100) NOT NULL,-- blocked,active,closed
	CATEGORY VARCHAR (100) NOT NULL,	
	ORDER_NUM INT NOT NULL,	
	DESCRIPTION VARCHAR (500) NOT NULL,	
       CREATED_SID   VARCHAR(37) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_SID   VARCHAR(37),
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID)
);

CREATE TABLE GATE_TYPE( 
	ID VARCHAR(37) NOT NULL,
	NAME VARCHAR (100) NOT NULL,
	CREATED_BY    VARCHAR(37) NOT NULL,
	CREATED_ON    TIMESTAMP NOT NULL,
	UPDATED_BY    VARCHAR(37),
	UPDATED_ON    TIMESTAMP,
	PRIMARY KEY (ID)
);
